FROM node:latest

# Maintainer
MAINTAINER Manuel DUQUESNOY <manuel.duquesnoy@free.fr>

# Create app directory
WORKDIR /usr/app

# Install app dependencies
COPY package.json /usr/app/
RUN npm install

#Expose on port 8069
EXPOSE 8069

#RUN the app
CMD [ "node", "server.js" ]